version: 2.1
orbs:
  node: circleci/node@5
  docker: circleci/docker@3.0.0

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  build-and-push:
    environment:
      DOCKER_IMAGE: pvha663/demo-react-docker
      DOCKER_TAG: latest
    docker:
      - image: circleci/python:3.7
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      - run:
          name: Push Docker Image
          command: docker push $DOCKER_IMAGE:$DOCKER_TAG
      - run:
          name: Show Digest
          command: |
            DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $DOCKER_IMAGE:$DOCKER_TAG)
            echo "Digest is: $DIGEST"

workflows:
  build-and-push:
    jobs:
      - test-node
      - build-and-push:
          requires:
            - test-node
          filters:
            branches:
              only:
                - main
