version: 2.1
orbs:
  node: circleci/node@5
  docker: circleci/docker@2.0.1

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  build-and-push:
    environment:
      DOCKER_IMAGE: pvha663/react-docker2
      DOCKER_TAG: latest
    executor: docker/default
    steps:
      - setup_remote_docker
      - checkout
      - docker/login:
          username: DOCKER_USER
          password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          name: Show Digest
          command: echo "Digest is: $(docker inspect --format='{{index .RepoDigests 0}}' $DOCKER_IMAGE:$DOCKER_TAG)"

workflows:
  build-and-push:
    jobs:
      - test-node
      - build-and-push:
          requires:
            - test-node
          filters:
            branches:
              only:
                - main
